# Markdown linting configuration
default: true

# MD013: Line length
MD013:
  line_length: 100
  code_blocks: false
  tables: false

# MD033: Allow inline HTML (for badges, etc.)
MD033: false

# MD041: First line in file should be a top-level heading
MD041: false

# MD046: Code block style
MD046:
  style: fenced

# MD024: Multiple headings with the same content
MD024:
  siblings_only: true
